steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discord-bot', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-bot']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'discord-bot'
      - '--image=gcr.io/$PROJECT_ID/discord-bot'
      - '--region=us-central1'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--port=8080'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--min-instances=1'
      - '--max-instances=1'
      - '--cpu-allocation=always'
      - '--set-env-vars=DISCORD_TOKEN=$$DISCORD_TOKEN,SUPABASE_URL=$$SUPABASE_URL,SUPABASE_SERVICE_KEY=$$SUPABASE_SERVICE_KEY,GOOGLE_APPLICATION_CREDENTIALS=$$GOOGLE_APPLICATION_CREDENTIALS,PORT=8080'
    secretEnv: 
      - 'DISCORD_TOKEN'
      - 'SUPABASE_URL' 
      - 'SUPABASE_SERVICE_KEY'
      - 'GOOGLE_APPLICATION_CREDENTIALS'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/discord-token/versions/latest
      env: 'DISCORD_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-service-key/versions/latest
      env: 'SUPABASE_SERVICE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/google-application-credentials/versions/latest
      env: 'GOOGLE_APPLICATION_CREDENTIALS'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/discord-bot'